version: "3.9"

services:
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.17
    container_name: elasticsearch1
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana1:
    image: docker.elastic.co/kibana/kibana:7.17.17
    container_name: kibana1
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch1

  backend:
    build: ./daar_library
    container_name: backend
    command: ["/wait-for-es.sh", "http://elasticsearch1:9200", "gunicorn", "daar_library.wsgi:application", "--bind", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    volumes:
      - ./daar_library:/app
    depends_on:
      elasticsearch1:
        condition: service_started

  frontend:
    build: ./library-frontend
    container_name: frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

volumes:
  esdata:
